script:
  - git clone https://github.com/erikzenker/inotify-cpp && cd inotify-cpp && mkdir build && cd build && cmake .. && make -j && sudo make install && cd .. && rm -rf inotify-cpp
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make -j

sudo: required
dist: bionic

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-7
            - g++-7-multilib
            - libboost-all-dev
      env: CXX=g++-7


