# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: run-vcpkg@0
    inputs:
      vcpkgArguments: 'boost-filesystem boost-system'
  - script: mkdir build; cd build; cmake ..; make; cpack
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: run-vcpkg@0
    inputs:
      vcpkgArguments: 'boost-filesystem boost-system'
  - script: mkdir build; cd build; cmake ..; make; cpack
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: run-vcpkg@0
    inputs:
      vcpkgArguments: 'boost-filesystem boost-system'
  - script: mkdir build; cd build; cmake ..; make; cpack
